services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUNNER_VERSION: ${RUNNER_VERSION:-2.321.0}
    image: ${REGISTRY_URL}/github-runner:${RUNNER_VERSION}
    environment:
      - RUNNER_REPO=${RUNNER_REPO}
      - RUNNER_TOKEN=${RUNNER_TOKEN}
      - NODE_VERSION=${NODE_VERSION}
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - RUNNER_LABELS=${RUNNER_LABELS:-self-hosted}
      # RUNNER_NAME will be set by the container
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    deploy:
      mode: replicated
      update_config:
        parallelism: 1
      rollback_config:
        parallelism: 1
      replicas: 1
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    networks:
      - runner-network

networks:
  runner-network:
    driver: bridge

# Specify the Docker registry authentication for pulling the image
x-credentials:
  registry:
    url: ${REGISTRY_URL}
    username: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}
